### ISSUE TITLE
Rison error on empty query parameters

### ISSUE THREAD

**Issue by Zasa-san** [huridocs/uwazidocs#5318]
**Describe the bug**
`rison` is throwing an error on `DocumentTypesList.js:153` when the url parameters have an empty query, eg: `/library/?q=`, causing a 500 on the page. This error is showing up on the notifications channel. 

```
3:53 PM: 2022-11-15T15:53:00.670Z [demo] requestId: 9927 
url: /library/?q=
query: {
 "q": ""
}
TypeError: Cannot read properties of null (reading 'length')
    at rison.parser.readValue (/opt/uwazi/cores/core-1.93.1/node_modules/rison-node/js/rison.js:389:11)
    at rison.parser.parse (/opt/uwazi/cores/core-1.93.1/node_modules/rison-node/js/rison.js:355:22)
    at Object.rison.decode (/opt/uwazi/cores/core-1.93.1/node_modules/rison-node/js/rison.js:301:14)
    at DocumentTypesList.renderSingleType (/opt/uwazi/cores/core-1.93.1/app/react/Library/components/DocumentTypesList.js:152:38)
    at /opt/uwazi/cores/core-1.93.1/app/react/Library/components/DocumentTypesList.js:213:41
    at Array.map (<anonymous>)
    at DocumentTypesList.renderGroupType (/opt/uwazi/cores/core-1.93.1/app/react/Library/components/DocumentTypesList.js:213:18)
    at /opt/uwazi/cores/core-1.93.1/app/react/Library/components/DocumentTypesList.js:228:23
    at Array.map (<anonymous>)
    at DocumentTypesList.render (/opt/uwazi/cores/core-1.93.1/app/react/Library/components/DocumentTypesList.js:226:13)
    at d (/opt/uwazi/cores/core-1.93.1/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:38:231)
    at $a (/opt/uwazi/cores/core-1.93.1/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:39:16)
    at a.b.render (/opt/uwazi/cores/core-1.93.1/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:44:476)
    at a.b.read (/opt/uwazi/cores/core-1.93.1/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:44:18)
    at renderToString (/opt/uwazi/cores/core-1.93.1/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:54:364)
    at renderComponentWithRoot (/opt/uwazi/cores/core-1.93.1/app/react/ServerRouter.js:55:52)
original error: {}
```

**To Reproduce**
1. Go to the library with the following url: `/library/?q=`

**Expected behavior**
Manage the empty parameters without a 500

**Comment by daneryl** [comment]
We think we should manage all rison parse errors and not throw a 500 on any of them, and throw a 400 (Bad Request) instead.

**Comment by fnocetti** [comment]
> We think we should manage all rison parse errors and not throw a 500 on any of them, and throw a 400 (Bad Request) instead.

Kind of agree. The thrown 500 is a side effect of the client failing during server-side rendering. If the client is throwing an unexpected error (unhandled rison decode error) I think the server should still throw a 500. I think the correct solution is that the client gracefully handles the rison error (as an input validation problem) and renders whatever is needed, server-side rendered or not.

As a side note: keep in mind this is not the only way to trigger this. Any invalid rison string would do the trick, e.g. `?q=(`.
