### ISSUE TITLE
Entity creation with relationship metadata is not checking for the existence of the relationship type

### ISSUE THREAD

**Issue by fnocetti** [huridocs/uwazidocs#5596]
**Describe the bug**
When creating an entity for a template that has a relationship property, it is not checking that the relationship type associated to the property actually exists. This causes problems later in the listing and reading of entities.

**To Reproduce**
1. Have templates `A` and `B`.
2. Create a relationship type `relType1`.
3. Add to `A` a relationship property that points to template `B` using the type `relType1`.
4. Create an entity `B1` of type `B`
5. Start to create an entity of type `A` and assign `B1` in the relationship field, **but don't save it yet**.
6. In other tab, go to the settings and delete `relType1`
7. Back to the original tab, save the entity that was being created.

**Current behavior**
The entity is created but you are showed a server error. In the logs it will show errors of the following shape
```
TypeError: Cannot read properties of undefined (reading 'name')
    at getGroupData (uwazi/app/api/relationships/groupByRelationships.js:9:84)
    at uwazi/app/api/relationships/groupByRelationships.js:26:23
    at Array.forEach (<anonymous>)
    at groupRelationships (uwazi/app/api/relationships/groupByRelationships.js:25:17)
    at app/api/relationships/relationships.js:211:78
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```
Because of this, the library and the entity view won't work properly.

**Expected behavior**
You should be presented with a validation error and not being allowed to create the entity.

**Additional context**
This also happens with the public forms, but the sender is not presented with any errors.

Related to #5595

**Comment by fnocetti** [comment]
We agreed that fixing #5595 would make this bug unreproducible, so the PR for that issue would fix this one as well.

**Comment by daneryl** [comment]
> We agreed that fixing #5595 would make this bug unreproducible, so the PR for that issue would fix this one as well.

I do not understand how #5601 fixes this issue ? it is only validating on delete, can you explain please ? the issue describes how creation does not validate that the relation type exists. the PR only validates that you can not delete a relation type that is being used, i understand this fixes some cases, but not validation on entity creation ?

**Comment by fnocetti** [comment]
This is fixed in relationships v2 and should be closed after the deprecation and migration.
