### ISSUE TITLE
Blinking 404 on wrong page

### ISSUE THREAD

**Issue by txau** [huridocs/uwazidocs#7073]
When navigating to a page/wrongURL the 404 is seen for sec and then replaced with a blank screen.

[Screencast from 2024-07-30 11-42-00.webm](https://github.com/user-attachments/assets/09e9863e-2700-475f-b307-2d0e2e5cc173)

**Comment by RafaPolit** [comment]
Konz mentions this could be related to the error handling in pages.  We should definitely know what is the culprit to determine priority and possible fix.

**Comment by txau** [comment]
Update: now it doesn't show the 404 page after blinking, and we get this error on the console:

Uncaught Error: Minified React error #422; visit https://reactjs.org/docs/error-decoder.html?invariant=422 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at react-dom.production.min.js:209:75
    at Ds (react-dom.production.min.js:206:204)
    at Ac (react-dom.production.min.js:293:79)
    at vu (react-dom.production.min.js:279:389)
    at gu (react-dom.production.min.js:279:362)
    at ou (react-dom.production.min.js:267:300)
    at O (scheduler.production.min.js:13:203)
    at MessagePort.S (scheduler.production.min.js:14:128)

**Comment by txau** [comment]
This bug has evolved and now shows

<img width="3424" height="908" alt="Image" src="https://github.com/user-attachments/assets/ab6e0b32-b2a4-4375-87bb-bba153a00f2c" />

which is better than a blank page, but still wrong. We need a simple 404.

**Comment by mfacar** [comment]
#8426 Fixes blinking 404 error on not found pages by improving error handling in PageViewer component. Updates error structure support and adds map error handling for custom pages (the reason the fallback component was not rendered).
