### ISSUE TITLE
Add more info to this error message

### ISSUE THREAD

**Issue by txau** [huridocs/uwazidocs#7193]
It would be great to know the instance and the failing URL

```
4:47 PM: 2024-09-04T16:47:54.075Z [localhost] 
TypeError: Only absolute URLs are supported
```

**Comment by txau** [comment]
Extra info 

```
2024-10-04T08:09:02.133Z [localhost] 
TypeError: Only absolute URLs are supported
    at getNodeRequestOptions (/opt/uwazi/cores/core-1.187.0-rc4/node_modules/node-fetch/lib/index.js:1327:9)
    at /opt/uwazi/cores/core-1.187.0-rc4/node_modules/node-fetch/lib/index.js:1440:19
    at new Promise (<anonymous>)
    at fetch (/opt/uwazi/cores/core-1.187.0-rc4/node_modules/node-fetch/lib/index.js:1437:9)
    at module.exports (/opt/uwazi/cores/core-1.187.0-rc4/node_modules/isomorphic-fetch/fetch-npm-node.js:8:19)
    at _fetch (/opt/uwazi/cores/core-1.187.0-rc4/app/shared/JSONRequest.js:108:10)
    at Object.get (/opt/uwazi/cores/core-1.187.0-rc4/app/shared/JSONRequest.js:157:32)
    at InformationExtraction.requestResults (/opt/uwazi/cores/core-1.187.0-rc4/app/api/services/informationextraction/InformationExtraction.js:147:51)
    at InformationExtraction.saveSuggestions (/opt/uwazi/cores/core-1.187.0-rc4/app/api/services/informationextraction/InformationExtraction.js:286:41)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /opt/uwazi/cores/core-1.187.0-rc4/app/api/services/informationextraction/InformationExtraction.js:548:11
    at async Object.processResults (/opt/uwazi/cores/core-1.187.0-rc4/app/api/services/informationextraction/InformationExtraction.js:533:7)
    at async TaskManager.checkForResults (/opt/uwazi/cores/core-1.187.0-rc4/app/api/services/tasksmanager/TaskManager.js:113:9)
    at async Repeater.start (/opt/uwazi/cores/core-1.187.0-rc4/app/api/utils/Repeater.js:16:7)
original error: {}
```

**Comment by txau** [comment]
This error seems to be gone. Closing for now.
