### ISSUE TITLE
OCR fails if metadata extractor is running

### ISSUE THREAD

**Issue by gabriel-piles** [huridocs/uwazidocs#7544]
When Uwazi receives OCR results with metadata extraction enabled, the following error occurs:

TypeError: Cannot read properties of undefined (reading 'template')
    at /uwazi/app/api/suggestions/eventListeners.ts:138:10
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Promise.all (index 0)
    at async EventsBus.emit (uwazi/app/api/eventsbus/EventsBus.ts:19:7)
    at async Object.save (uwazi/app/api/files/files.ts:49:7)
    at async processPDF (uwazi/app/api/files/processDocument.ts:14:18)
    at async processFiles (uwazi/app/api/services/ocr/OcrManager.ts:107:22)
    at async uwazi/app/api/services/ocr/OcrManager.ts:138:7
    at async Object.processResults (uwazi/app/api/services/ocr/OcrManager.ts:126:3)
    at async TaskManager.checkForResults (uwazi/app/api/services/tasksmanager/TaskManager.ts:119:9)
    at async Repeater.start (uwazi/app/api/utils/Repeater.js:24:7)

**To Reproduce**

1. Start Uwazi with 

```
yarn blank state
export EXTERNAL_SERVICES=true
yarn hot
```

3. Activate metadata extractor and ocr flags

```
  "ocrServiceEnabled": true
  "features": {
    "ocr": {
      "url": "http://localhost:5051"
    },
    "metadataExtraction": {
      "url": "http://localhost:5056"
    },
    "metadata-extraction": true
  },
```

4. Start OCR service

```
git clone https://github.com/huridocs/pdf-document-layout-analysis-async.git
cd pdf-document-layout-analysis-async
make start
```

5. Send a PDF to OCR

**Comment by RafaPolit** [comment]
@gabriel-piles is this prior to the incorporation of OCR into the other services? Or is this still an issue?

**Comment by gabriel-piles** [comment]
@RafaPolit yes, it is prior to the OCR server change. 

And, it is still an issue.

**Comment by daneryl** [comment]
OcrManager process was running without the proper permissions and when metadata extractor picks up from the ocr file creation  the process can not get the entity if its not public.
I did work on a more generic way to give workers proper permissions, until now every taskManager was responsable of setting up the permissions for its own process, i have changed this so that we can se up a default permission  used now in worker.ts since all the workers need to run with a super permission because this processes do not belong to any user.

**Comment by daneryl** [comment]
After trying to replicate this i discovered this only happens locally when using EXTERNAL_SERVICES=true production/staging environments worked fine.
